--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Bad4Second/SimpleShopFork
build-by-default: true
branches:
- main
projects:
  SimpleShopFork:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
...
